# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# Some distros (like NixOS) may not autostart fcitx5 after booting.
exec-once = pgrep fcitx5 || fcitx5 -d
